export const DESCRIPTION = {
    ABOUT: 'Since the first time I created my own website when I was 10 years old. I took a fancy to do creation of all about digital content. Such as animation, game and tool software. It defined my choice of my career in the future. Most of time, I was able to learn new skills of programming by my self. However, I was concerned about the design and the thinking of the users. The point was the key I decided to major in media design. Because of that, I am good at both of development and user experience. \n\nAccording to the experience of starting a startup company with my partners. I assimilated the knowlodge of leading teams to process with positive energy to co-work together. \n\nThis years, I did full time jobs of front end developer and freelace jobs of full stack developer for few times. That is interesting to have chance to create different kind of products. I like to work with people cooperatively. Also I am excited to face challenge and solve them. Additionally, it is interesting to research new technology to me. With my skills of front end development and knowledge of back end. Hoping to have the opportunity to make more great works with great people.',
    PROJECTS:
        'That is exciting to design plugins and tools. I usually have idea when I developed the products. It will be more and more.',
    WORK_ENGLISH_AGENCY:
        'Fortuitously, we had a idea with a partner company. It was a publishing platform for the recruiters of English schools to share knowledge. Helped the students who were interested to know the schools or culture before they went.\n\nThe feature was static content in server rendering. Each article is easy to be found by search engine even if the recruiters publish article any time.\n\nBesides front end development, I built server rendering server in Node.js for adding each article files when anyone publishing.',
    WORK_NOPER:
        "We created a chatbot as a startup idea for focusing on main tasks in working conversation at messaging tools like LINE, or Facebook Messager.\n\nTeam managers could assign missions to members. Chatbot would notify each one who was assigned to. Also the managers would be notified when the works' state was changed or completed.\n\nTwo partners and I processed the product. I was in charge of chatbot and web app development, and also designed user interface.",
    WORK_SHIBATV:
        'As a senior frontend engineer in an awesome web frontend team, I had a chance to design an on-boarding training kit for new members to understand what we do and how we do. The basic idea is to develop a simple OTT platform website with requesting tech stacks. And running on kanban also choosing the optional feature by self in limited time.\n\nThere is a demo to show the result of the traning I designed. ',
    WORKS: 'Experience in various web app projects in frontend jobs. Most of them are built with different features and tech stacks, such as vanilla JavaScript, React, Vue.js and AngularJS. Here is a selection of my recent works.',
};

export const TITLE = {};
