export const DESCRIPTION = {
    ABOUT: ` Since I first created my own website at the age of 10, I've been captivated by the world of digital content creation, encompassing games, animations, and toolkits. This early fascination shaped my career aspirations. While I mostly taught myself new programming skills, I was keenly aware of the importance of design and user-centric thinking. This realization led me to pursue a major in media design. As a result, I excel in both development and user experience. \n\nAs a web frontend engineer for several years, I have achieved numerous milestones, not only in developing various types of web applications but also in leading web frontend teams to successfully complete projects. I have led web frontend teams in developing OTT streaming platforms and their CMS. Additionally, I created a modularized OTT platform starter kit for setting up new products and designed an onboarding training kit for learning how to use Kanban, understand flowcharts, and develop an OTT platform MVP with specific tech stacks. \n\nThe skills I have acquired are not solely for task execution; they also enable me to strategize improvements in performance, maintainability, and workflow. Additionally, my background in launching a startup and my major have equipped me with the capacity to think from different perspectives. My experience has endowed me with the ability to strike a balance between technical proficiency and coordination, making me a flexible engineer capable of tackling diverse products.`,
    PROJECTS:
        'That is exciting to design plugins and tools. I usually have idea when I developed the products. It will be more and more.',
    WORK_ENGLISH_AGENCY:
        'Fortuitously, we had a idea with a partner company. It was a publishing platform for the recruiters of English schools to share knowledge. Helped the students who were interested to know the schools or culture before they went.\n\nThe feature was static content in server rendering. Each article is easy to be found by search engine even if the recruiters publish article any time.\n\nBesides front end development, I built server rendering server in Node.js for adding each article files when anyone publishing.',
    WORK_NOPER:
        "We created a chatbot as a startup idea for focusing on main tasks in working conversation at messaging tools like LINE, or Facebook Messager.\n\nTeam managers could assign missions to members. Chatbot would notify each one who was assigned to. Also the managers would be notified when the works' state was changed or completed.\n\nTwo partners and I processed the product. I was in charge of chatbot and web app development, and also designed user interface.",
    WORK_SHIBATV:
        'As a senior frontend engineer in an awesome web frontend team, I had a chance to design an on-boarding training kit for new members to understand what we do and how we do. The basic idea is to develop a simple OTT platform website with requesting tech stacks. And running on kanban also choosing the optional feature by self in limited time.\n\nThere is a demo to show the result of the traning I designed. ',
    WORKS: 'Experience in various web app projects in frontend jobs. Most of them are built with different features and tech stacks, such as vanilla JavaScript, React, TypeScript, Vue.js, and AngularJS. Here is a selection of my recent works.',
};

export const TITLE = {};
